apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../elx-docs

patches:
  - target:
      kind: Ingress
      name: elx-docs
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: docs-lab.elastx.cloud
      - op: replace
        path: /spec/rules/0/host
        value: docs-lab.elastx.cloud
